version: '2'

services:
  entropy-migration-dev:
    container_name: entropy-migration-dev
    build: .
    volumes:
      - ./:/opt/lib/

  entropy-migration-db:
    image: mysql:5.6
    container_name: entropy-migration-db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TERM: xterm
    volumes:
      - entropy-migration-db-data:/var/lib/mysql

volumes:
  entropy-migration-db-data:
    driver: local
